name: Build and Push Docker UI demo-hello Image

on:
  push:
    branches:
      - dev-k8-deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0 # Adjust the Node.js version as needed

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t maharera-ui-main-app:maharera-ui-main .
        

      - name: Push Docker image to Docker Hub
        run: |
          docker tag maharera-ui-main-app:maharera-ui-main ${{ secrets.DOCKERHUB_USERNAME }}/maharera-ui-main-app:maharera-ui-main
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/maharera-ui-main-app:maharera-ui-main
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
